# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Python CI

on:
  push:
    # Run for all branches (feature/*, bugfix/*, etc.) but skip deleted ref noise
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Principle of least privilege (defaults to read-only if unspecified)
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUNBUFFERED: '1'
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: ${{ github.workspace }}
    # Plaid secrets intentionally omitted in CI; app guards missing credentials.
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Show environment details
        shell: bash
        run: |
          python --version
          pip --version
          which python
          pwd
          ls -1
      - name: Install base + dev dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage
      - name: Lint
        shell: bash
        run: |
          # Stop build on critical errors first
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Then run a full report without failing the build (style warnings)
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests with coverage
        env:
          FLASK_ENV: testing
          SECRET_KEY: test-secret-key
          PLAID_ENV: sandbox
        shell: bash
        run: |
          coverage run -m pytest -q --maxfail=1 --junitxml=pytest-report.xml
          coverage xml -o coverage.xml
          coverage report -m
      - name: Enforce minimum coverage
        shell: bash
        run: coverage report --fail-under=50 -m
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            pytest-report.xml
            coverage.xml

    # Deployment steps would go here - e.g., to Heroku, Fly.io, etc.
    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: "billpay-app"
    #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
