name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      PYTHONUNBUFFERED: '1'
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: ${{ github.workspace }}
      FLASK_ENV: testing
      SECRET_KEY: test-secret-key
      PLAID_ENV: sandbox

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage
      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          coverage run -m pytest -q --maxfail=1 --junitxml=pytest-report.xml || exit 1
          coverage xml -o coverage.xml
          coverage report -m
      - name: Coverage threshold
        run: coverage report --fail-under=50 -m

    # (Artifacts omitted intentionally to reduce editor warnings; add back if needed.)

    # Deployment steps would go here - e.g., to Heroku, Fly.io, etc.
    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: "billpay-app"
    #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
